final_space = true
version = 2
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[[blocks]]
alignment = "left"
type = "prompt"
newline = true

  [[blocks.segments]]
  foreground = "magenta"
  style = "plain"
  template = "@{{ .UserName }}"
  type = "session"

  [[blocks.segments]]
  foreground = "blue"
  style = "plain"
  template = " {{ .Path }}"
  type = "path"

    [blocks.segments.properties]
    style = "folder"

  [[blocks.segments]]
  style = "plain"
  template = " <red>git:(</>{{ .HEAD }}{{ if gt .Ahead 0 }} ↑{{.Ahead}}{{ end }}{{ if gt .Behind 0 }} ↓{{.Behind}}{{ end }}{{ if .Working.Changed }} {{ .Working.String }}{{ end }}{{ if .Staging.Changed }} {{ .Staging.String }}{{ end }}<red>)</>"
  type = "git"

    [blocks.segments.properties]
    branch_icon = ""
    commit_icon = '@'
    fetch_status = true

  [[blocks.segments]]
  foreground = "cyan"
  style = "plain"
  template = """

➜"""
  type = "text"

