#+TITLE: Emacs Literate Config - Development
#+AUTHOR: Karan Ahlawat
#+PROPERTY: header-args:emacs-lisp :tangle ./dev.el

Here lies my WIP setup for my development needs and wants.


* Magit

First, the Magit package because it's absolutely great to use.

#+begin_src emacs-lisp

  (use-package magit
    :custom
    (magit-display-buffer-function #'magit-display-buffer-same-window-except-diff-v1))

#+end_src

* Project Management

Gonna use the built-in project.el package (starting from Emacs 28+) for project management. Here's I'm defining keybinds for convenience.

#+begin_src emacs-lisp
  
  (korv/leader-keys
    "p"  '(:ignore t :which-key "project")
    "pp" '(project-switch-project :which-key "Switch project")
    "pf" '(project-find-file :which-key "Project find file")
    "pd" '(project-dired :which-key "Dired project root")
    "pe" '(project-eshell :which-key "Eshell project root")
    "pa" '(project-forget-project :which-key "Remove project")
    "pk" '(project-kill-buffers :which-key "Kill project buffers")
    "pc" '(project-async-shell-command :which-key "Async cmd project root"))

#+end_src

* Languages
** Lisp

For (Common) Lisp, we're gonna use the SLY package and configure it appropriately.

#+begin_src emacs-lisp

  (use-package sly
      :defer t
      :config
      (setq inferior-lisp-program "sbcl"))

#+end_src

** Elixir

We're gonna setup elixir mode and see how it goes from there.

#+begin_src emacs-lisp

  (use-package elixir-mode
    :config
    (add-hook 'elixir-mode-hook
              (lambda ()
                (add-hook 'before-save-hook 'elixir-format nil t))))

#+end_src

And we are going to setup alchemist even though it might be outdated.

#+begin_src emacs-lisp

  (use-package alchemist)

#+end_src

* Language server integration

Language servers are nice to provide completions, jumps and the like. But they require a client, and here we're gonna use eglot ( could switch to lsp-mode if this doesn't work well ).

#+begin_src emacs-lisp

  (use-package eglot
    :ensure t
    :config
    (add-to-list 'eglot-server-programs '(elixir-mode "/usr/lib/elixir-ls/language_server.sh"))
    (add-to-list 'eglot-ignored-server-capabilities :hoverProvider))

#+end_src
