#+TITLE: Emacs Literate Config - Development
#+AUTHOR: Karan Ahlawat
#+PROPERTY: header-args:emacs-lisp :tangle ./dev.el

Here lies my WIP setup for my development needs and wants.


* Magit

First, the Magit package because it's absolutely great to use.

#+begin_src emacs-lisp

  (use-package magit
    :custom
    (magit-display-buffer-function #'magit-display-buffer-same-window-except-diff-v1))

  (define-key magit-mode-map (kbd "s") 'magit-status)

#+end_src


* Project Management

Gonna use the built-in project.el package (starting from Emacs 28+) for project management. Here's I'm defining keybinds for convenience.

#+begin_src emacs-lisp

  ;; (korv/leader-keys
  ;;   "p"  '(:ignore t :which-key "project")
  ;;   "pp" '(project-switch-project :which-key "Switch project")
  ;;   "pf" '(project-find-file :which-key "Project find file")
  ;;   "pd" '(project-dired :which-key "Dired project root")
  ;;   "pe" '(project-eshell :which-key "Eshell project root")
  ;;   "pa" '(project-forget-project :which-key "Remove project")
  ;;   "pk" '(project-kill-buffers :which-key "Kill project buffers")
  ;;   "pc" '(project-async-shell-command :which-key "Async cmd project root"))

#+end_src

Also adding the ability to use .root for defining project-root

#+begin_src emacs-lisp
  (defvar korv/project-root-list '(".git" "mix.exs" ".project"))

  (defun member-project-list-p (file)
    (member file korv/project-root-list))

  (defun project-definer-p (dir)
    (let ((dir-files (directory-files dir)))
      (and (mapcar #'member-project-list-p dir-files))))
  

  (defun korv/project-try-explicit (dir)
    "Find a super-directory of DIR containing a root file."
    (locate-dominating-file dir #'project-definer-p))

  (defmethod project-root ((project string))
    project)

  (add-hook 'project-find-functions
      #'korv/project-try-explicit)
#+end_src

* Syntax Checking and Linting

Flycheck can use various linters and checkers for real-time code checking.

#+begin_src emacs-lisp

  (use-package flycheck
    :defer t
    :ensure t
    :init
    (global-flycheck-mode)
    :config
    (setq flycheck-javascript-eslint-executable "eslint_d"))

#+end_src

* Languages
** Lisp

For (Common) Lisp, we're gonna use the SLY package and configure it appropriately.

#+begin_src emacs-lisp

  (use-package sly
      :defer t
      :config
      (setq inferior-lisp-program "sbcl"))

#+end_src

And parinfer-rust-mode for editing lisps.

#+begin_src emacs-lisp
  
  (use-package parinfer-rust-mode
    :hook
    (emacs-lisp-mode . parinfer-rust-mode)
    (lisp-mode . parinfer-rust-mode)
    (common-lisp-mode . parinfer-rust-mode)
    :init
    (setq parinfer-rust-auto-download t))

#+end_src

** Elixir

We're gonna setup elixir mode and see how it goes from there.

#+begin_src emacs-lisp

  (use-package elixir-mode
    :defer t
    :config
    (add-hook 'elixir-mode-hook
              (lambda ()
                (add-hook 'before-save-hook 'elixir-format nil t))))

#+end_src

And we are going to setup alchemist even though it might be outdated.

#+begin_src emacs-lisp

  (use-package alchemist
    :defer t
    :hook (elixir-mode . alchemist-mode))

#+end_src

** Javascript

Here we go again

#+begin_src emacs-lisp

  (use-package js2-mode
    :mode ("\\.js\\'")
    :defer t
    :config
    (setq js2-basic-offset 2))

#+end_src

* Language server integration

Language servers are nice to provide completions, jumps and the like. But they require a client, and here we're gonna use eglot ( could switch to lsp-mode if this doesn't work well ).

#+begin_src emacs-lisp

  (use-package eglot
    :ensure t
    :defer t
    :hook
    ((elixir-mode js2-mode) . eglot-ensure)
    :config
    (add-to-list 'eglot-server-programs '(elixir-mode . ("/usr/lib/elixir-ls/language_server.sh")))
    (add-to-list 'eglot-ignored-server-capabilities :hoverProvider))

#+end_src


* Highlight numbers

Cuz why not?

#+begin_src emacs-lisp

  (use-package highlight-numbers
    :defer t
    :config
    (add-hook 'prog-mode-hook 'highlight-numbers-mode))

#+end_src


* Treesitter test

Treesitter is an incrememntal parsing library

#+begin_src emacs-lisp

  (defface tree-sitter-hl-face:warning
    '((default :inherit font-lock-warning-face))
    "Face for parser errors"
    :group 'tree-sitter-hl-faces)

  (defun korv/tree-sitter-common ()
    (unless font-lock-defaults
      (setq font-lock-defaults '(nil)))
    (setq tree-sitter-hl-use-font-lock-keywords nil)
    (tree-sitter-mode +1)
    (tree-sitter-hl-mode +1))

  (defun korv/elixir-tree-sitter ()
    (setq
     tree-sitter-hl-default-patterns
     (read
      (concat
       "["
       (s-replace "#match?" ".match?"
                  (f-read-text (expand-file-name "~/Secondary/dev/tree-sitter/elixir/highlights.scm")))
       "]")))

    (korv/tree-sitter-common))
  

  (use-package tree-sitter
    :ensure t
    :hook ((elixir-mode . korv/elixir-tree-sitter))
    :custom-face
    (tree-sitter-hl-face:operator ((t)))
    (tree-sitter-hl-face:variable ((t)))
    (tree-sitter-hl-face:function.method.call ((t)))
    (tree-sitter-hl-face:property ((t)))

    :config
    (setq tree-sitter-debug-highlight-jump-region t)
    (setq tree-sitter-debug-jump-buttons t))


  (use-package tree-sitter-langs
    :ensure t
    :after tree-sitter)

#+end_src
