#+TITLE: Emacs Literate Config - Development
#+AUTHOR: Karan Ahlawat
#+PROPERTY: header-args:emacs-lisp :tangle ./dev.el

Here lies my WIP setup for my development needs and wants.


* Magit

First, the Magit package because it's absolutely great to use.

#+begin_src emacs-lisp

  (use-package magit
    :custom
    (magit-display-buffer-function #'magit-display-buffer-same-window-except-diff-v1))

  (define-key magit-mode-map (kbd "s") 'magit-status)

#+end_src


* Project Management

Going to use =projectile= 

#+begin_src emacs-lisp

  (use-package project
    :config
    (defvar project-root-markers '("Cargo.toml" "mix.exs" ".project" "package.json"))

    (defun korv/project-find-root (path)
      (let* ((this-dir (file-name-as-directory (file-truename path)))
             (parent-dir (expand-file-name (concat this-dir "../")))
             (system-root-dir (expand-file-name "/")))
        (cond
         ((korv/project-root-p this-dir) (cons 'transient this-dir))
         ((equal system-root-dir this-dir) nil)
         (t (korv/project-find-root parent-dir)))))

    (defun korv/project-root-p (path)
      (let ((results (mapcar (lambda (marker)
                               (file-exists-p (concat path marker)))
                             project-root-markers)))
        (eval `(or ,@ results))))

    (add-to-list 'project-find-functions #'korv/project-find-root))
      

#+end_src

* Syntax Checking and Linting

Flycheck can use various linters and checkers for real-time code checking.

#+begin_src emacs-lisp

  (use-package flycheck
    :defer t
    :ensure t
    :init
    (global-flycheck-mode)
    :config
    (setq flycheck-javascript-eslint-executable "eslint_d"))

#+end_src

* Languages
** Lisp

For (Common) Lisp, we're gonna use the SLY package and configure it appropriately.

#+begin_src emacs-lisp

  (use-package sly
      :defer t
      :config
      (setq inferior-lisp-program "sbcl"))

#+end_src

And parinfer-rust-mode for editing lisps.

#+begin_src emacs-lisp
  
  (use-package parinfer-rust-mode
    :hook
    (emacs-lisp-mode . parinfer-rust-mode)
    (lisp-mode . parinfer-rust-mode)
    (common-lisp-mode . parinfer-rust-mode)
    :init
    (setq parinfer-rust-auto-download t))

#+end_src

** Elixir

We're gonna setup elixir mode and see how it goes from there.

#+begin_src emacs-lisp

  (use-package elixir-mode
    :defer t
    :config
    (add-hook 'elixir-mode-hook
              (lambda ()
                (add-hook 'before-save-hook 'elixir-format nil t))))

  (use-package flycheck-credo
    :after elixir-mode
    :config
    (flycheck-credo-setup))
 
#+end_src

And we are going to setup alchemist even though it might be outdated.

#+begin_src emacs-lisp

  (use-package alchemist
    :defer t
    :hook (elixir-mode . alchemist-mode))

#+end_src

** Javascript

Here we go again

#+begin_src emacs-lisp

  (use-package js2-mode
    :mode ("\\.js\\'")
    :defer t
    :config
    (setq js2-basic-offset 2))

#+end_src

** TypeScript

#+begin_src emacs-lisp

  (use-package typescript-mode
    :mode ("\\.ts\\'")
    :defer t)

#+end_src

** HTML

Using emmet-mode to write HTML

#+begin_src emacs-lisp

    (use-package web-mode
      :mode "\\.html\\'"
      :init
      (add-to-list 'auto-mode-alist '("\\.heex\\'" . mhtml-mode))
      :config
      (setq web-mode-enable-html-entities-fontification t)
      (setq web-mode-auto-close-style 1)
      (setq web-mode-engines-alist '(("elixir" . "\\.ex\\'"))))
                                  

    (use-package emmet-mode
      :hook ((web-mode . emmet-mode)
             (mhtml-mode . emmet-mode)
             (poly-elixir-web-mode . emmet-mode))
           
      :config
      (define-key emmet-mode-keymap (kbd "TAB") #'emmet-expand-line))
#+end_src

** HEEx

#+begin_src emacs-lisp

  (use-package polymode
    :ensure t
    :mode ("\.ex$" . poly-elixir-web-mode)
    :config
    (define-hostmode poly-elixir-hostmode :mode 'elixir-mode)
    (define-innermode poly-live-view-expr-elixir-innermode
      :mode 'web-mode
      :head-matcher (rx line-start (* space) "~H" (= 3 (char "\"'")) line-end)
      :tail-matcher (rx line-start (* space) (= 3 (char "\"'")) line-end)
      :head-mode 'host
      :tail-mode 'host
      :allow-nested nil
      :keep-in-mode 'host
      :fallback-mode 'host)
    (define-polymode poly-elixir-web-mode
      :hostmode 'poly-elixir-hostmode
      :innermodes '(poly-live-view-expr-elixir-innermode)))

#+end_src

** Prettier

We add prettier for code formatting.

#+begin_src emacs-lisp

  (use-package prettier)

#+end_src

** Prisma

Prisma is an ORM for JS/TS.

#+begin_src emacs-lisp

  (load (expand-file-name "emacs-prisma-mode/prisma-mode" user-emacs-directory))

#+end_src

** Solidity

A toast to my baby steps into the web3 world.

#+begin_src emacs-lisp

  (use-package solidity-mode
    :mode ("\\.sol\\'")
    :defer t)

  (use-package solidity-flycheck
    :after solidity-mode)

#+end_src


* Language server integration

Language servers are nice to provide completions, jumps and the like. But they require a client, and here we're gonna use eglot ( could switch to lsp-mode if this doesn't work well ).

#+begin_src emacs-lisp

  (use-package eglot
    :ensure t
    :defer t
    :init
    (setq eglot-sync-connect 1
          eglot-connect-timeout 10
          eglot-autoshutdown t
          eglot-send-changes-idle-time 0.5
          eglot-auto-display-help-buffer nil)
    (setq eglot-stay-out-of '(flycheck))
    :hook
    ((c-mode c++-mode elixir-mode js2-mode typescript-mode prisma-mode) . eglot-ensure)
    :bind
    (:map eglot-mode-map
          ("C-c l r"   . 'eglot-rename)
          ("C-c l a"   . 'eglot-code-actions)
          ("C-c l f t" . 'eglot-find-typeDefinition)
          ("C-c l f d" . 'eglot-find-declaration)
          ("C-c l f m" . 'eglot-find-implementation)
          ("C-c l q"   . 'eglot-code-action-quickfix)
          ("C-c l b"   . 'eglot-format-buffer)
          ("C-c l o"   . 'eglot-code-action-organize-imports)
          ("C-c l h"   . 'eldoc-box-eglot-help-at-point)
          ("C-c l c"   . 'consult-eglot-symbols))
    :config
    (add-to-list 'eglot-ignored-server-capabilities :hoverProvider)
    (add-to-list 'eglot-server-programs '(prisma-mode . ("prisma-language-server" "--stdio")))
    (add-to-list 'eglot-server-programs '(solidity-mode . ("solc" "--lsp")))
    (add-to-list 'eglot-server-programs '((c++-mode c-mode) "clangd"))

    (setq eglot-confirm-server-initiated-edits nil)

    (defconst eglot-eclipse-jdt-home "/home/karan/.java/eclipse.jdt.ls/org.eclipse.jdt.ls.product/target/repository/plugins/org.eclipse.equinox.launcher_1.5.700.v20200207-2156.jar")

    (defun eglot-eclipse-jdt-contact (interactive)
      (let ((cp (getenv "CLASSPATH")))
        (setenv "CLASSPATH" (concat cp ":" eglot-eclipse-jdt-home))
        (unwind-protect (eglot--eclipse-jdt-contact nil)
          (setenv "CLASSPATH" cp))))

    (setcdr (assq 'java-mode eglot-server-programs) #'eglot-eclipse-jdt-contact)

    (add-hook 'java-mode-hook 'eglot-ensure))
#+end_src

We also add consult eglot for symbols and stuff, and defer the shutdown of the server.

#+begin_src elisp
  (use-package consult-eglot
    :config
    (define-key eglot-mode-map [remap xref-find-apropos] #'consult-eglot-symbols))

  ;; Defer Eglot shutting down servers for a few seconds

  (defun eglot--defer-server-shutdown (fn &optional server)
    (cl-letf (((symbol-function #'eglot-shutdown)
               (lambda (server)
                 (run-at-time 5
                              nil
                              (lambda (server)
                                (unless (eglot--managed-buffers server)
                                  (eglot-shutdown server)))
                              server))))
      (funcall fn server)))

  (advice-add #'eglot--managed-mode
              :around #'eglot--defer-server-shutdown)

#+END_SRC

* Highlight numbers

Cuz why not?

#+begin_src emacs-lisp

  (use-package highlight-numbers
    :defer t
    :config
    (add-hook 'prog-mode-hook 'highlight-numbers-mode))

#+end_src


* Treesitter

Treesitter is an incrememntal parsing library

#+begin_src emacs-lisp
  
  (defun korv/enable-tree-sitter-hl ()
    (tree-sitter-hl-mode +1))

  (use-package tree-sitter
    :ensure t
    :config
    (setq tree-sitter-debug-highlight-jump-region t)
    (setq tree-sitter-debug-jump-buttons t)
    (add-hook 'js2-mode-hook #'korv/enable-tree-sitter-hl)
    (add-hook 'c++-mode-hook #'korv/enable-tree-sitter-hl)
    (global-tree-sitter-mode +1))


  (use-package tree-sitter-langs
    :ensure t
    :after tree-sitter)

#+end_src

* Docs

Eldoc and a couple of feature-addition packages.

#+begin_src emacs-lisp

  (use-package eldoc
    :hook
    (eglot-connect . eldoc-mode))

  (use-package eldoc-box
    :commands (eldoc-box-hover-at-point-mode))

#+end_src
