#+TITLE: Emacs Literate Config - Development
#+AUTHOR: Karan Ahlawat
#+PROPERTY: header-args:emacs-lisp :tangle ./dev.el

Here lies my WIP setup for my development needs and wants.


* Magit

First, the Magit package because it's absolutely great to use.

#+begin_src emacs-lisp

  (use-package magit
    :custom
    (magit-display-buffer-function #'magit-display-buffer-same-window-except-diff-v1))

  (define-key magit-mode-map (kbd "s") 'magit-status)

#+end_src


* Project Management

Going to use =project-x= which is a package based off of the project.el package built into emacs.

#+begin_src emacs-lisp

  (use-package project-x
    :load-path "~/.config/emacs/project-x/"
    :after project
    :config
    (setq project-x-local-identifier '(".project" "mix.exs" ".gitignore" "Cargo.toml")))

#+end_src

* Syntax Checking and Linting

Flycheck can use various linters and checkers for real-time code checking.

#+begin_src emacs-lisp

  (use-package flycheck
    :defer t
    :ensure t
    :init
    (global-flycheck-mode)
    :config
    (setq flycheck-javascript-eslint-executable "eslint_d"))

#+end_src

* Languages
** Lisp

For (Common) Lisp, we're gonna use the SLY package and configure it appropriately.

#+begin_src emacs-lisp

  (use-package sly
      :defer t
      :config
      (setq inferior-lisp-program "sbcl"))

#+end_src

And parinfer-rust-mode for editing lisps.

#+begin_src emacs-lisp
  
  (use-package parinfer-rust-mode
    :hook
    (emacs-lisp-mode . parinfer-rust-mode)
    (lisp-mode . parinfer-rust-mode)
    (common-lisp-mode . parinfer-rust-mode)
    :init
    (setq parinfer-rust-auto-download t))

#+end_src

** Elixir

We're gonna setup elixir mode and see how it goes from there.

#+begin_src emacs-lisp

  (use-package elixir-mode
    :defer t
    :config
    (add-hook 'elixir-mode-hook
              (lambda ()
                (add-hook 'before-save-hook 'elixir-format nil t))))

#+end_src

And we are going to setup alchemist even though it might be outdated.

#+begin_src emacs-lisp

  (use-package alchemist
    :defer t
    :hook (elixir-mode . alchemist-mode))

#+end_src

** Javascript

Here we go again

#+begin_src emacs-lisp

  (use-package js2-mode
    :mode ("\\.js\\'")
    :defer t
    :config
    (setq js2-basic-offset 2))

#+end_src

* Language server integration

Language servers are nice to provide completions, jumps and the like. But they require a client, and here we're gonna use eglot ( could switch to lsp-mode if this doesn't work well ).

#+begin_src emacs-lisp

  (use-package eglot
    :ensure t
    :defer t
    :hook
    ((elixir-mode js2-mode java-mode) . eglot-ensure)
    :bind
    (:map eglot-mode-map
          ("C-c C-l C-r" . 'eglot-rename)
          ("C-c C-c C-a" . 'eglot-code-actions)
          ("C-c C-f C-t" . 'eglot-find-typeDefinition)
          ("C-c C-f C-d" . 'eglot-find-declaration)
          ("C-c C-f C-m" . 'eglot-find-implementation)
          ("C-c C-c C-q" . 'eglot-code-action-quickfix)
          ("C-c C-b"     . 'eglot-format-buffer)
          ("C-c C-c C-o" . 'eglot-code-action-organize-imports)
          ("C-c C-h"     . 'eldoc-box-eglot-help-at-point))
    :config
    (add-to-list 'eglot-server-programs '(elixir-mode . ("/usr/lib/elixir-ls/language_server.sh")))
    (add-to-list 'eglot-ignored-server-capabilities :hoverProvider))

#+end_src


* Highlight numbers

Cuz why not?

#+begin_src emacs-lisp

  (use-package highlight-numbers
    :defer t
    :config
    (add-hook 'prog-mode-hook 'highlight-numbers-mode))

#+end_src


* Treesitter

Treesitter is an incrememntal parsing library

#+begin_src emacs-lisp

  (defface tree-sitter-hl-face:warning
    '((default :inherit font-lock-warning-face))
    "Face for parser errors"
    :group 'tree-sitter-hl-faces)

  (defun korv/tree-sitter-common ()
    (unless font-lock-defaults
      (setq font-lock-defaults '(nil)))
    (setq tree-sitter-hl-use-font-lock-keywords nil)
    (tree-sitter-mode +1)
    (tree-sitter-hl-mode +1))

  (defun korv/elixir-tree-sitter ()
    (setq
     tree-sitter-hl-default-patterns
     (read
      (concat
       "["
       (s-replace "#match?" ".match?"
                  (f-read-text (expand-file-name "~/Secondary/dev/tree-sitter/elixir/highlights.scm")))
       "]")))

    (korv/tree-sitter-common))

  (defun korv/js-tree-sitter ()
    (korv/tree-sitter-common))

  (use-package tree-sitter
    :ensure t
    :hook ((elixir-mode . korv/elixir-tree-sitter))
    :hook ((js2-mode . korv/js-tree-sitter))
    :custom-face
    (tree-sitter-hl-face:operator ((t)))
    (tree-sitter-hl-face:variable ((t)))
    (tree-sitter-hl-face:function.method.call ((t)))
    (tree-sitter-hl-face:property ((t)))

    :config
    (setq tree-sitter-debug-highlight-jump-region t)
    (setq tree-sitter-debug-jump-buttons t))

  (use-package tree-sitter-langs
    :ensure t
    :after tree-sitter)

#+end_src

* Docs

Eldoc and a couple of feature-addition packages.

#+begin_src emacs-lisp

  (use-package eldoc
    :hook
    (eglot-connect . eldoc-mode))

  (use-package eldoc-box
    :commands (eldoc-box-hover-at-point-mode)
    :hook
    (eldoc-mode . eldoc-box-hover-at-point-mode))

#+end_src
