#+TITLE: Emacs Literate Configuration
#+AUTHOR: Karan Ahlawat
#+PROPERTY: header-args:emacs-lisp :tangle ./init.el

This is my personal Emacs configuration, in a literate format using the powerful Org mode. It is an effort to setup a minimal (yet fully functional) Emacs setup.

* Defining Variables

Let's define some variables to keep this DRY.

#+begin_src emacs-lisp

  (defvar korv/default-font-size 150)
  (defvar korv/default-variable-font-size 150)
  (defvar korv/frame-transparency '(95 . 90))
  (defvar korv/font-name "Iosevka Nerd Font Mono")

#+end_src

* Garbage Collection Start 

Change the garbage collection defaults for better performance and startup times.

#+begin_src emacs-lisp

  (setq gc-cons-threshold (* 50 1000 1000))

#+end_src

And a function to measure the startup performance

#+begin_src emacs-lisp

  (defun korv/display-startup-time ()
    (message "Emacs loaded in %s with %d garbage collections."
             (format "%.2f seconds"
                     (float-time
                      (time-subtract after-init-time before-init-time)))
             gcs-done))

  ;; Add the startup function to the emacs-startup-hook
  (add-hook 'emacs-startup-hook #'korv/display-startup-time)

#+end_src

Also gonna set the custom file to be a seperate file so it doesn't mess with my stuff.

#+begin_src emacs-lisp

  (setq custom-file (concat user-emacs-directory "custom.el"))
  (when (file-exists-p custom-file)
    (load custom-file))

#+end_src

* UI Configuration

Some basic UI changes for restorations!

#+begin_src emacs-lisp

  (setq inhibit-startup-message t)
  (scroll-bar-mode -1)
  (tool-bar-mode -1)
  (tooltip-mode -1)
  (set-fringe-mode 10)
  (menu-bar-mode -1)

  (setq visual-bell t)

#+end_src

Add we're gonna change some frame parameters to customize the look and behaviour (use a compositor for the transparency)

#+begin_src emacs-lisp

  (set-frame-parameter (selected-frame) 'alpha korv/frame-transparency)
  (add-to-list 'default-frame-alist `(alpha . ,korv/frame-transparency))
  (set-frame-parameter (selected-frame) 'fullscreen 'maximized)
  (add-to-list 'default-frame-alist '(fullscreen . maximized))

#+end_src

** Fonts

Let's set fonts so our editor doesn't look like a pleb

#+begin_src emacs-lisp

  (defun korv/set-font-faces ()
    (message "Setting font faces.")
    (set-face-attribute 'default nil :font korv/font-name :height korv/default-font-size :weight 'medium)
    (set-face-attribute 'fixed-pitch nil :font korv/font-name :height korv/default-font-size :weight 'medium)
    (set-face-attribute 'variable-pitch nil :font korv/font-name :height korv/default-variable-font-size :weight 'regular))

  (if (daemonp)
      (add-hook 'after-make-frame-functions
                (lambda (frame)
                  (with-selected-frame frame
                    (korv/set-font-faces))))
    (korv/set-font-faces))

#+end_src

* Sane-r defaults

Adding/changing some defaults here so that we don't lose our sanity. Dark Souls is fun, but not IRL.

#+begin_src emacs-lisp

  ;; Set <ESC> to escape globally
  (global-set-key (kbd "<escape>") 'keyboard-escape-quit)

  ;; Change some global defaults
  (column-number-mode)
  (global-display-line-numbers-mode t)
  (setq tab-always-indent t)
  (defalias 'yes-or-no-p 'y-or-n-p)
  (show-paren-mode 1)
  (setq backup-direcotry-alist '(("." . "~/.cache/emacssaves"))
        create-lockfiles nil
        initial-major-mode 'fundamental-mode
        initial-scratch-message nil
        tab-width 2)

  (setq-default
   auto-save-list-file-prefix nil
   cursor-in-non-selected-windows nil
   fill-column 80
   help-window-select t
   indent-tabs-mode nil
   select-enable-clipboard t
   x-stretch-cursor t)

  (blink-cursor-mode 0)
  (delete-selection-mode t)
  ;; Disable line numbers for some modes
  (dolist (mode '(org-mode-hook
                  term-mode-hook
                  shell-mode-hook
                  eshell-mode-hook))
    (add-hook mode (lambda () (display-line-numbers-mode -1))))

  (set-default-coding-systems 'utf-8)

  (setq split-width-threshold 0
        split-height-threshold nil)

#+end_src

* Packages

Let's setup some package repositories, so our Emacs isn't so lonely.

#+begin_src emacs-lisp

  (require 'package)

  (setq package-archives '(("melpa" . "https://melpa.org/packages/")
                           ("org" . "https://orgmode.org/elpa/")
                           ("nongnu" . "https://elpa.nongnu.org/nongnu/")
                           ("elpa" . "https://elpa.gnu.org/packages/")))

  (package-initialize)
  (unless package-archive-contents
    (package-refresh-contents))

#+end_src

And bootstrap use-package, our biggest weapon to keep things cleaner. Sorta.

#+begin_src emacs-lisp

  (unless (package-installed-p 'use-package)
    (package-install 'use-package))

  ;; Setup use-package
  (require 'use-package)
  (setq use-package-always-ensure t)

#+end_src

And now, the packages I have so far!

** NO LITTERING ON MY LAWN!

Keeps our Emacs user directory clean (.emacs.d)

#+begin_src emacs-lisp

  (use-package no-littering
    :ensure t
    :config
    (require 'recentf)
    (add-to-list 'recentf-exclude no-littering-var-directory)
    (add-to-list 'recentf-exclude no-littering-etc-directory))

  (setq make-backup-files nil)

  (make-directory (expand-file-name "tmp/auto-saves/" user-emacs-directory) t)

  (setq auto-save-list-file-prefix (expand-file-name "tmp/auto-saves/sessions/" user-emacs-directory)
        auto-save-file-name-transforms `((".*" ,(expand-file-name "tmp/auto-saves" user-emacs-directory) t)))
#+end_src

** Autoupdate

Automatic update for packages

#+begin_src emacs-lisp

  (use-package auto-package-update
    :custom
    (auto-package-update-interval 7)
    (auto-package-update-prompt-before-update t)
    (auto-package-update-hide-results t)
    :config
    (auto-package-update-maybe)
    (auto-package-update-at-time "09:00"))


#+end_src

** Themes, because the world is an ugly place

Shoutout Prost, and his magnificent beard!

#+begin_src emacs-lisp

  (use-package modus-themes
    :config
    (setq modus-themes-hl-line '(intense)))

#+end_src

And everyone who contributed to the Doom themes (currently rocking laserwave). I set the theme in the config section itself, passing t so that it doesn't ask me on every run if I trust the themes.

#+begin_src emacs-lisp

  (use-package doom-themes)

#+end_src

And spacemacs themes.

#+begin_src emacs-lisp

  (setq spacemacs-theme-org-bold t
        spacemacs-theme-underline-parens t)

#+end_src

And ujelly theme

#+begin_src emacs-lisp

      (use-package ujelly-theme
        :config
        (load-theme 'ujelly-theme t))

#+end_src

** Which Key

Imagine knowing how to be proficient with your editor of choice :)

#+begin_src emacs-lisp

  (use-package which-key
    :defer 0
    :diminish which-key-mode
    :config
    (which-key-mode)
    (setq which-key-idle-delay 0.5))

#+end_src

** All The Icons

Gonna add them sweet sweet icons. Don't forget to run M-x all-the-icons-install-fonts RET to actually install the fonts using this package

#+begin_src emacs-lisp

  (use-package all-the-icons
    :ensure t)

#+end_src

Also we're gonna use the icons in dired, so let's set that up

#+begin_src emacs-lisp

  (use-package all-the-icons-dired
    :config
    (add-hook 'dired-mode-hook 'all-the-icons-dired-mode))

#+end_src

** Smartparens

Parenthesis editing made easier?

#+begin_src emacs-lisp

  (use-package smartparens
    :config
    (require 'smartparens-config)

    (smartparens-global-mode +1))
#+end_src

** Completion

I'm gonna keep it minimal (as stated in the start) and opt for Vertico, Consult, Orderless and Corfu with Cape

*** Vertico

A completion UI framework, working in mysterious minibuffers.

#+begin_src emacs-lisp

  (use-package vertico
    :ensure t
    :bind (:map vertico-map
                ("C-g" . vertico-exit))
    :custom
    (vertico-cycle t)
    :init
    (vertico-mode))
#+end_src

Shows the most recently used completions first.

#+begin_src emacs-lisp
  (use-package savehist
    :init
    (savehist-mode))
#+end_src

Marginalia for more information in completions and the like.

#+begin_src emacs-lisp

  (use-package marginalia
    :after vertico
    :ensure t
    :custom
    (marginalia-annotators '(marginalia-annotators-heavy marginalia-annotators-light nil))
    :init
    (marginalia-mode))

#+end_src

*** Orderless

Advanced completion and filtering in said completion. Really cool stuff.

#+begin_src emacs-lisp

  (use-package orderless
    :ensure t
    :custom
    (completion-styles '(orderless))
    (completion-category-defaults nil)
    (completion-cattegory-overrides '((file (styles partial-completion)))))

#+end_src

*** Consult

The workhorse for a lot of work, goes really well with Vertico to provide it the information to show in the minibuffers.

#+begin_src emacs-lisp

  (use-package consult
    :init
    (setq register-preview-delay 0)
    (setq register-preview-function #'consult-register-format)
    (advice-add #'register-preview :override #'consult-register-window)
    (advice-add #'completing-read-multiple :override #'consult-completing-read-multiple)
    (setq xref-show-xrefs-function #'consult-xref
          xref-show-definitions-function #'consult-xref)
    :config
    (setq consult-preview-key 'any)
    (setq consult-narrow-key "<") ;; (kbd "C-+")
    (setq consult-project-root-function
          (lambda ()
            (when-let (project (project-current))
              (car (project-roots project))))))

#+end_src

Not setting up any keybinds for consult right here, I prefer to do that using General. You may proceed as you wish.

*** Corfu

It is a region completion package that builds on Emacs' in-built functionality instead of it's own, like Company does. Anything can plug into it as long as it has a proper completion-at-point-function.

#+begin_src emacs-lisp

  (use-package corfu
    :custom
    (corfu-cycle t)
    (corfu-auto t)
    (corfu-quit-at-boundary nil)
    (corfu-quit-no-match t)
    (corfu-preselect-first t)
    (corfu-echo-documentation nil)
    :init
    (corfu-global-mode))

#+end_src

And Cape, for completion-at-point-functions which are nice but not included in Emacs by default.

#+begin_src emacs-lisp
  ;; TODO: Remap keybinds?

  (use-package cape
    :init
    (add-to-list 'completion-at-point-functions #'cape-file)
    (add-to-list 'completion-at-point-functions #'cape-dabbrev)
    (add-to-list 'completion-at-point-functions #'cape-abbrev)
    (add-to-list 'completion-at-point-functions #'cape-keyword))

  (use-package dabbrev)

#+end_src

*** kind-icon

icons for corfu

#+begin_src emacs-lisp

  (use-package kind-icon
    :ensure t
    :after corfu
    :custom
    (kind-icon-default-face 'corfu-default) ; to compute blended backgrounds correctly
    :config
    (add-to-list 'corfu-margin-formatters #'kind-icon-margin-formatter))

#+end_src

** UI Packages

Some packages for a better UI experience

*** Doom Modeline

I like the Doom Emacs Modeline much better than the default one, so here goes.

#+begin_src emacs-lisp

  (use-package doom-modeline
    :ensure t
    :init
    (doom-modeline-mode 1)
    :config
    (setq doom-modeline--eglot t
          doom-modeline--project-root t))

#+end_src

*** Dashboard

A nice dashboard greets you when you run Emacs.

#+begin_src emacs-lisp

  (use-package dashboard
    :custom
    (initial-buffer-choice (lambda () (get-buffer "*dashboard*")))
    (dashboard-banner-logo "")
    (dashboard-startup-banner 'logo)
    (dashboard-center-content t)
    (dashboard-show-shortcuts t)
    (dashboard-projects-backend 'project-el)
    (dashboard-items '((recents . 5)
                       (projects . 5)))
    (dashboard-set-heading-icons t)
    (dashboard-set-file-icons t)
    (dashboard-set-init-info t)
    :hook
    (dashboard-mode . (lambda () (setq global-hl-line-mode nil)))
    :config
    (dashboard-setup-startup-hook))

  (use-package page-break-lines
    :after dashboard
    :config
    (page-break-lines-mode))
#+end_src

And bracket pair matching

#+begin_src emacs-lisp

  (use-package rainbow-delimiters
    :hook (prog-mode . rainbow-delimiters-mode))

#+end_src

* Keybinds!

The meat and potatoes, as I like to call it.

** Meow

#+begin_src emacs-lisp
  (defun meow-setup ()
    (setq meow-cheatsheet-layout meow-cheatsheet-layout-qwerty)
    (meow-motion-overwrite-define-key
     '("j" . meow-next)
     '("k" . meow-prev)
     '("SPC q f" . delete-frame)
     '("SPC f l" . consult-line))
    (meow-leader-define-key
     ;; SPC j/k will run the original command in MOTION state.
     '("j" . "H-j")
     '("k" . "H-k")
     ;; Use SPC (0-9) for digit arguments.
     '("1" . meow-digit-argument)
     '("2" . meow-digit-argument)
     '("3" . meow-digit-argument)
     '("4" . meow-digit-argument)
     '("5" . meow-digit-argument)
     '("6" . meow-digit-argument)
     '("7" . meow-digit-argument)
     '("8" . meow-digit-argument)
     '("9" . meow-digit-argument)
     '("0" . meow-digit-argument)
     '("/" . meow-keypad-describe-key)
     '("?" . meow-cheatsheet))
    (meow-normal-define-key
     '("0" . meow-expand-0)
     '("9" . meow-expand-9)
     '("8" . meow-expand-8)
     '("7" . meow-expand-7)
     '("6" . meow-expand-6)
     '("5" . meow-expand-5)
     '("4" . meow-expand-4)
     '("3" . meow-expand-3)
     '("2" . meow-expand-2)
     '("1" . meow-expand-1)
     '("-" . negative-argument)
     '(";" . meow-reverse)
     '("," . meow-inner-of-thing)
     '("." . meow-bounds-of-thing)
     '("[" . meow-beginning-of-thing)
     '("]" . meow-end-of-thing)
     '("a" . meow-append)
     '("A" . meow-open-below)
     '("b" . meow-back-word)
     '("B" . meow-back-symbol)
     '("c" . meow-change)
     '("d" . meow-delete)
     '("D" . meow-backward-delete)
     '("e" . meow-next-word)
     '("E" . meow-next-symbol)
     '("f" . meow-find)
     '("g" . meow-cancel-selection)
     '("G" . meow-grab)
     '("h" . meow-left)
     '("H" . meow-left-expand)
     '("i" . meow-insert)
     '("I" . meow-open-above)
     '("j" . meow-next)
     '("J" . meow-next-expand)
     '("k" . meow-prev)
     '("K" . meow-prev-expand)
     '("l" . meow-right)
     '("L" . meow-right-expand)
     '("m" . meow-join)
     '("n" . meow-search)
     '("o" . meow-block)
     '("O" . meow-to-block)
     '("p" . meow-yank)
     '("q" . meow-quit)
     '("Q" . meow-goto-line)
     '("r" . meow-replace)
     '("R" . meow-swap-grab)
     '("s" . meow-kill)
     '("t" . meow-till)
     '("u" . meow-undo)
     '("U" . meow-undo-in-selection)
     '("v" . meow-visit)
     '("w" . meow-mark-word)
     '("W" . meow-mark-symbol)
     '("x" . meow-line)
     '("X" . meow-goto-line)
     '("y" . meow-save)
     '("Y" . meow-sync-grab)
     '("z" . meow-pop-selection)
     '("'" . repeat)
     '("<escape>" . mode-line-other-buffer)))

  (use-package meow
    :ensure t
    :config
    (meow-setup)
    (meow-global-mode 1))
#+end_src

* Org Mode

One of the best pieces of software I've come in contact with. Although I don't utilize it to it's full potential, it has more potential than Harry Potter. Ok, maybe that isn't saying much. But it's cracked.

A function (from EFS) for setting up better font rendering in Org files.

#+begin_src emacs-lisp

  (defun korv/org-font-setup ()

    ;; Replace list hyphen with dot
    (font-lock-add-keywords 'org-mode
                            '(("^ *\\([-]\\) "
                               (0 (prog1 () (compose-region (match-beginning 1) (match-end 1) ""))))))

    ;; Set faces for heading levels
    (dolist (face '((org-level-1 . 1.2)
                    (org-level-2 . 1.1)
                    (org-level-3 . 1.05)
                    (org-level-4 . 1.0)
                    (org-level-5 . 1.1)
                    (org-level-6 . 1.1)
                    (org-level-7 . 1.1)
                    (org-level-8 . 1.1)))
      (set-face-attribute (car face) nil :font "JetBrainsMono Nerd Font" :weight 'regular :height (cdr face)))

    ;; Ensure fixed pitch appears as fixed pitch
    (set-face-attribute 'org-block nil :foreground nil :inherit 'fixed-pitch)
    (set-face-attribute 'org-table nil :inherit 'fixed-pitch)
    (set-face-attribute 'org-formula nil  :inherit 'fixed-pitch)
    (set-face-attribute 'org-code nil     :inherit '(shadow fixed-pitch))
    (set-face-attribute 'org-table nil    :inherit '(shadow fixed-pitch))
    (set-face-attribute 'org-verbatim nil :inherit '(shadow fixed-pitch))
    (set-face-attribute 'org-special-keyword nil :inherit '(font-lock-comment-face fixed-pitch))
    (set-face-attribute 'org-meta-line nil :inherit '(font-lock-comment-face fixed-pitch))
    (set-face-attribute 'org-checkbox nil  :inherit 'fixed-pitch)
    (set-face-attribute 'line-number nil :inherit 'fixed-pitch)
    (set-face-attribute 'line-number-current-line nil :inherit 'fixed-pitch))

#+end_src

Some minor modes to enable when we enter org-mode

#+begin_src emacs-lisp

  (defun korv/org-mode-setup ()
    (org-indent-mode)
    (variable-pitch-mode 1)
    (visual-line-mode 1))

#+end_src

And now we configure the package. Beauty of use-package I think.

#+begin_src emacs-lisp

  (use-package org
    :pin org
    :commands (org-capture org-agenda)
    :hook (org-mode . korv/org-mode-setup)
    :config
    (require 'org-tempo)

    ;; Add <el and <sh snippet for quicker code blocks
    (add-to-list 'org-structure-template-alist '("sh" . "src shell"))
    (add-to-list 'org-structure-template-alist '("el" . "src emacs-lisp"))

    (setq org-confirm-babel-evaluate nil
          org-ellipsis " ▾"
          org-agenda-files (list "~/Documents/org/Agenda.org")
          org-latex-pdf-process '("tectonic -X compile --outdir=%o %f"))

    (advice-add 'org-refile :after 'org-save-all-org-buffers)

    (korv/org-font-setup)

    ;; Enable emacs-lisp in the code blocks
    (org-babel-do-load-languages
     'org-babel-load-languages
     '((emacs-lisp . t))))


#+end_src

Some visual changes in the org buffer apart from fonts

#+begin_src emacs-lisp

;; Nicer heading bullets
(use-package org-bullets
  :hook (org-mode . org-bullets-mode)
  :custom
  (org-bullets-bullet-list '("" "○" "●" "○" "●" "○" "●")))

;; Center org buffer
(defun korv/org-mode-visual-fill ()
  (setq visual-fill-column-width 100
	visual-fill-column-center-text t)
  (visual-fill-column-mode 1))

(use-package visual-fill-column
  :hook (org-mode . korv/org-mode-visual-fill))

#+end_src

Add auto-tangle when the file changes

#+begin_src emacs-lisp

  (defun korv/org-babel-tangle-config ()
    (when (member (buffer-file-name)
                   (list
                    (expand-file-name "~/.dotfiles/.config/emacs/Emacs.org")
                    (expand-file-name "~/.dotfiles/.config/emacs/Development.org")))
      (let ((org-confirm-babel-evaluate nil))
        (org-babel-tangle))))

  (add-hook 'org-mode-hook (lambda () (add-hook 'after-save-hook #'korv/org-babel-tangle-config)))

#+end_src

* Eshell

Eshell is a shell written entirely in elisp, and while it can be quirky at first, I find it to be very useful. 

First, some helper functions

#+begin_src emacs-lisp

  (defun read-file (file-path)
    (with-temp-buffer
      (insert-file-contents file-path)
      (buffer-string)))

  (defun korv/map-line-to-status-char (line)
    (cond ((string-match "^?\\? " line) "?")))

  (defun korv/get-git-status-prompt ()
    (let ((status-lines (cdr (process-lines "git" "status" "--porcelain" "-b"))))
      (seq-uniq (seq-filter 'identity (mapcar 'kd/map-line-to-status-char status-lines)))))

  (defun korv/get-prompt-path ()
    (let* ((current-path (eshell/pwd))
           (git-output (shell-command-to-string "git rev-parse --show-toplevel"))
           (has-path (not (string-match "^fatal" git-output))))
      (if (not has-path)
          (abbreviate-file-name current-path)
        (string-remove-prefix (file-name-directory git-output) current-path))))

#+end_src

And now the actual prompt function.

#+begin_src emacs-lisp

  (defun korv/eshell-prompt ()
    (let ((current-branch (magit-get-current-branch)))
      (concat
       "\n"
       (propertize (korv/get-prompt-path) 'face `(:foreground "#2fafff"))
       (when current-branch
         (concat
          (propertize " on " 'face `(:foreground "white"))
          (propertize (concat " " current-branch) 'face `(:foreground "#f48cd4"))))
       (if (= (user-uid) 0)
           (propertize "\n#" 'face `(:foreground "red2"))
         (propertize "\n➜" 'face `(:foreground "#f48cd4")))
       (propertize " " 'face `(:foreground "white")))))

#+end_src

And now a configuration function

#+begin_src emacs-lisp

  (defun korv/eshell-configure ()

    (require 'magit)

    (use-package xterm-color)

    (push 'eshell-tramp eshell-modules-list)
    (push 'xterm-color-filter eshell-preoutput-filter-functions)
    (delq 'eshell-handle-ansi-color eshell-output-filter-functions)

    ;; Save command history
    (add-hook 'eshell-pre-command-hook 'eshell-save-some-history)

    (add-hook 'eshell-before-prompt-hook
              (lambda ()
                (setq xterm-color-preserve-properties t)))

    (add-to-list 'eshell-output-filter-functions 'eshell-truncate-buffer)

    (add-hook 'eshell-pre-command-hook
              (lambda () (setenv "TERM" "xterm-256color")))
    (add-hook 'eshell-post-command-hook
              (lambda () (setenv "TERM" "dumb")))

    (eshell-hist-initialize)

    (setq eshell-history-size 5000
          eshell-buffer-maximum-lines 5000
          eshell-hist-ignoredups t
          eshell-destroy-buffer-when-process-dies t
          eshell-highlight-prompt t
          eshell-prefer-lisp-functions nil
          eshell-scroll-to-bottom-on-output t
          eshell-prompt-function 'korv/eshell-prompt
          eshell-prompt-regexp "^➜ ")

    (setenv "PAGER" "cat"))

#+end_src

Putting it all together, here's what we get

#+begin_src emacs-lisp

  (use-package eshell
    :after magit
    :hook
    (eshell-first-time-mode . korv/eshell-configure)
    (eshell-mode . (lambda () (corfu-mode -1)))
    :init
    (setq eshell-directory-name "~/.config/emacs/eshell/"
          eshell-aliases-file (expand-file-name "~/.config/emacs/eshell/aliases")))

  (use-package exec-path-from-shell
    :init
    (setq exec-path-from-shell-check-startup-files nil)
    :config
    (exec-path-from-shell-initialize))

#+end_src

* Development

Load the development elisp file.

#+begin_src emacs-lisp

  (load (expand-file-name "~/.config/emacs/dev.el"))
  (load (expand-file-name "~/.config/emacs/tree-sitter.el"))

#+end_src

* Garbage Collection End

And now we close off the GC :)

#+begin_src emacs-lisp

  (setq gc-cons-threshold (* 2 1000 1000))

#+end_src
