#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

dir="ox"
prev_name="0xProto"
new_font_name=('Leo' 'Proto')
font_name=${new_font_name[@]}
IFS=; sub_name=${new_font_name[*]}

# Create an empty array to store the file names
for file in ./$dir/*; do
	# Add the file name to the array
	IFS=\/ read -r base name font <<< $file
	IFS=- read -r name weight <<< $font
	$(pyftfreeze -R "'$prev_name/$font_name'" "$file" "./modout/$sub_name-$weight")
done
