[user]
name = "Karan Ahlawat"
email = "ahlawatkaran12@gmail.com"

[ui]
graph.style = "square"
pager = "delta"
editor = ["flatpak", "run", "re.sonny.Commit"]
diff-editor = "nvim"
default-command = "status"

[ui.diff]
format = "git"
