[tools]
usage = "latest"
node = "20"
java = "temurin-21"
"cargo:eza" = "latest"
"cargo:zoxide" = "latest"
tokei = "latest"
deno = "1"
"cargo:jj-cli" = "latest"
delta = "latest"
opam = "2.2"
coursier = "latest"
fzf = "latest"
elixir = "1.16"
erlang = "26"
bun = "1"
clojure = "1"
go = "latest"
"go:github.com/sqls-server/sqls" = "latest"

[settings]
experimental = true

[env]
