[tools]
usage = "latest"
node = "20"
java = "temurin-21"
"cargo:eza" = "latest"
"cargo:zoxide" = "latest"
tokei = "latest"
deno = "1.42.0"
"cargo:jj-cli" = "latest"
delta = "latest"
elixir = "1.16.2-otp-26"
erlang = "26"
ruby = "3"
python = "3.12"
bun = "1"
quarkus = "3"
ktlint = "latest"
opam = "2.2.0-beta2"

[settings]
experimental = true
