[tools]
usage = "latest"
node = "20"
java = "temurin-21"
"cargo:eza" = "latest"
"cargo:zoxide" = "latest"
tokei = "latest"
deno = "1.42.0"
"cargo:jj-cli" = "latest"
delta = "latest"
python = "3.12"
opam = "2.2.0-beta2"
coursier = "latest"
fzf = "latest"
elixir = "1.16"
erlang = "26"

[settings]
experimental = true
